### ISSUE TITLE
大佬您好 好像您的这个脚本现在会报错  有没有解决办法呢

### ISSUE THREAD

**Issue by zxrql** [QinJinYuan/juejin_books#1]

**Comment by zxrql** [comment]
D:\juejinxiaoce\juejin_books>node main.js
file:///D:/juejinxiaoce/juejin_books/utils.js:20
    const books = response.data.map((book) => ({
                                ^

TypeError: Cannot read properties of null (reading 'map')
    at getBooks (file:///D:/juejinxiaoce/juejin_books/utils.js:20:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (file:///D:/juejinxiaoce/juejin_books/main.js:8:19)

**Comment by zxrql** [comment]
或者加我QQ1960512171
